274806 update file names
osisoft/PI-Adapter-Azure-Event-Hubs-Docs pull request #41
Opened 2021-11-24 00:20 UTC by osisoft-mbishop

2021-11-24 06:25 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +        exec /PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-arm/OSIsoft.Data.System.Host
Per Alison's email, it looks like the underscore _ should be included after "arm". Also in the spreadsheet, there should be an underscore _ after Hubs instead of a dash -.

```suggestion
        exec /PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-arm_/OSIsoft.Data.System.Host
```

2021-11-24 06:26 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +        exec /PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-arm/OSIsoft.Data.System.Host --port:$portnum
```suggestion
        exec /PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-arm_/OSIsoft.Data.System.Host --port:$portnum
```

2021-11-24 06:26 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +        exec /PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-arm64/OSIsoft.Data.System.Host
```suggestion
        exec /PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-arm64_/OSIsoft.Data.System.Host
```

2021-11-24 06:27 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +        exec /PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-arm64/OSIsoft.Data.System.Host --port:$portnum
```suggestion
        exec /PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-arm64_/OSIsoft.Data.System.Host --port:$portnum
```

2021-11-24 06:27 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +        exec /PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-x64/OSIsoft.Data.System.Host
```suggestion
        exec /PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-x64_/OSIsoft.Data.System.Host
```

2021-11-24 06:28 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +        exec /PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-x64/OSIsoft.Data.System.Host --port:$portnum
```suggestion
        exec /PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-x64_/OSIsoft.Data.System.Host --port:$portnum
```

2021-11-24 06:28 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +    ADD ./PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-arm.tar.gz .
```suggestion
    ADD ./PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-arm_.tar.gz .
```

2021-11-24 06:28 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +    ADD ./PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-arm64.tar.gz .
```suggestion
    ADD ./PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-arm64_.tar.gz .
```

2021-11-24 06:28 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +    ADD ./PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-x64.tar.gz .
```suggestion
    ADD ./PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-x64_.tar.gz .
```

2021-11-24 06:29 UTC, rmuolic commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +2. Copy the `PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-<platform>.tar.gz` file to the same directory as the `Dockerfile`.
```suggestion
2. Copy the `PI-Adapter-for-Azure-Event-Hubs_1.0.1.239-<platform>_.tar.gz` file to the same directory as the `Dockerfile`.
```

2021-11-24 06:29 UTC, rmuolic requested changes
Per Alison's email, it looks like the underscore _ should be included after "arm". Also in the spreadsheet, there should be an underscore _ after Hubs instead of a dash -. Added suggestions throughout per spreadsheet.

2021-11-29 20:28 UTC, osisoft-mbishop commented on content/installation/install-pi-adapter-for-azure-event-hubs-using-docker.md
> +        exec /PI-Adapter-for-Azure-Event-Hubs-1.0.1.239-arm/OSIsoft.Data.System.Host
Thanks for these corrections @rmuolic.

2021-11-29 20:30 UTC, merged